name: Pull Request Workflow

on: pull_request

jobs:
  cloudformation-linter:
    runs-on: Ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@3

      - name: Linter install
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t ./vpc.yaml
          
        